### ISSUE TITLE
CMS pages not showing unless you hard reload

### ISSUE THREAD

**Issue by ghost** [SnowdogApps/magento2-cms-api#12]
Strange behavior of the plugin happens when you click on the footer menu, one of the links

"https://logima.io/offline-shopping" and https://logima.io/shop-by-voice, doesn't show up at first load, when you hard reload it (shift + command + r).

How do I solve this challenge? 

Thanks in advance!

**Comment by jochhop** [comment]
Hi @Decntdefalt could you please give us more details about the issue you're experiencing? if you use the API endpoints provided by the extension, there should not be problems with cache.

Are you using the API from a Magento shop? or are you accessing the API through an external app (such as vue storefront)?

**Comment by ghost** [comment]
> Hi @Decntdefalt could you please give us more details about the issue you're experiencing? if you use the API endpoints provided by the extension, there should not be problems with cache.
> 
> Are you using the API from a Magento shop? or are you accessing the API through an external app (such as vue storefront)?

This worked out great. Thanks! I think my problem was related to caching on VSF. Sorry for any confusion.

**Comment by jochhop** [comment]
Hi @Decntdefalt we're glad to hear that your problem is solved. Have a nice day!
