### ISSUE TITLE
Magento 2.4 Support?

### ISSUE THREAD

**Issue by boehsermoe** [SnowdogApps/magento2-cms-api#22]
We need to update magento to version 2.4. When does this module will support the new version?

**Comment by jochhop** [comment]
Hi @boehsermoe thanks for opening the issue, we have already in queue 2.4 tests, so we'll reply you as soon as we ensure it's compatible or not (and when it'll be compatible in case it's not)

**Comment by jochhop** [comment]
Hi @boehsermoe Magento 2.4 support has been introduced in the newer 1.9.0 release, thank you for the suggestion.
