### ISSUE TITLE
Add compatibility with PHP 7.4

### ISSUE THREAD

**Issue by andres-linares2211** [SnowdogApps/magento2-cms-api#25]
Magento 2.4 uses PHP 7.4 :+1:

**Comment by jochhop** [comment]
Hi @andres-linares2211 , thanks for opening the issue, we'll check it shortly, have a great day!

**Comment by jochhop** [comment]
Hi @andres-linares2211 , thanks again for your suggestion, we have added tested and added php 7.4 compatibility in `composer.json`

I am closing the issue
