### ISSUE TITLE
Magento 2.4.6 PHP 8.1

### ISSUE THREAD

**Issue by hielh** [SnowdogApps/magento2-cms-api#28]
Hey guys,
I'm using Magento 2.4.3 with PHP 7.4. 
When I try to upgrade to Magento 2.4.6 with PHP 8.1. this module blocked the upgrade : 
![image](https://github.com/SnowdogApps/magento2-cms-api/assets/909932/2e14af71-ac86-4a07-b129-7cc066100229)

**Comment by jochhop** [comment]
Hi @hielh , thank you for opening the issue, we have created an internal ticket and we'll let you know once this is verified and fixed,

have a great day!

**Comment by jochhop** [comment]
Hi @hielh PHP 8.1 and 8.2 have been tested and confirmed, there's a new tag available where you can get the changes: [1.11.0](https://github.com/SnowdogApps/magento2-cms-api/releases/tag/1.11.0)

I am closing this, thank you!

**Comment by hielh** [comment]
@jochhop thank you for your help
