### ISSUE TITLE
Disabled CMS block/pages

### ISSUE THREAD

**Issue by shkodasv** [SnowdogApps/magento2-cms-api#3]
Hello!
If the CMS block is disabled in Magento Admin, it should not appear on FE too. Could you please add this check? Thanks!

**Comment by jochhop** [comment]
Hi @shkodasv thanks for your request.

As the endpoints in this extension work similar as standard Magento 2 endpoints do, we think we should not add this feature.

If you want to get only enabled blocks/pages, there is a possibility to use searchCriteria parameter to filter the results.

For instance, to get only enabled blocks, you could use the following request:

`/rest/V1/snowdog/cmsBlock/search?searchCriteria[filter_groups][0][filters][0][field]=is_active&searchCriteria[filter_groups][0][filters][0][value]=1`

**Comment by shkodasv** [comment]
@jochhop Thanks for answer!
