### ISSUE TITLE
Magento Widgets/Custom blocks in CMS data

### ISSUE THREAD

**Issue by shkodasv** [SnowdogApps/magento2-cms-api#4]
Hi!
Would be really great if the Magento Widgets and Custom Blocks are processed correctly. Could you please add this option?

**Comment by jochhop** [comment]
Hi @shkodasv thanks for your request,

we are thinking about implementing such feature but it'll not come soon as the widgets logic is not so simple.

We are open to receive PRs meanwhile :)

**Comment by shkodasv** [comment]
@jochhop 
Ok, if we come up with idea we will provide the PR

**Comment by shkodasv** [comment]
@jochhop will you merge this PR to master ?

**Comment by jochhop** [comment]
Hi @shkodasv, the PR needs to be checked by another reviewer too (we're on it), but I guess it'll be accepted soon

**Comment by shkodasv** [comment]
Thanks!

**Comment by jochhop** [comment]
Closing this as it's already in develop
