### ISSUE TITLE
CMS Block/Pages List with store_id provided

### ISSUE THREAD

**Issue by anqaka** [SnowdogApps/magento2-cms-api#5]
when request all list of blocks or pages we get array of objects like:
```
{
    "items": [
        {
            "id": 7,
            "identifier": "example-block",
            "title": "Block title",
            "content": "Test block content",
            "creation_time": "2014-12-02 11:54:46",
            "update_time": "2014-12-02 11:54:46",
            "active": true
        },
        {
            "id": 11,
            "identifier": "example-block",
            "title": "Block title",
            "content": "Test block content",
            "creation_time": "2015-04-30 12:22:24",
            "update_time": "2016-04-04 12:11:57",
            "active": true
        }
     ]
}
```
There is no info about store_id inside. 
It will be great to get object with provided stode_ids, like:
 ```
{
    "items": [
        {
            "id": 7,
            "identifier": "example-block",
            "title": "Block title",
            "content": "Test block content",
            "creation_time": "2014-12-02 11:54:46",
            "update_time": "2014-12-02 11:54:46",
            "active": true,
            "store_ids": [1, 2]
        },
        {
            "id": 11,
            "identifier": "example-block",
            "title": "Block title",
            "content": "Test block content",
            "creation_time": "2015-04-30 12:22:24",
            "update_time": "2016-04-04 12:11:57",
            "active": true.
            "store_ids": [1, 3]
        }
     ]
}
```

**Comment by mcjwsk** [comment]
Hi @anqaka . While developing the solution we discovered some difficulties. The main issue is that this improvement requires changing return type in our endpoints. IMO this introduces unnecessary complexity.
I am thinking of creating a separate endpoint for retrieving links between blocks and stores.

Example:
```
GET /V1/snowdog/cmsBlock/:blockId/stores
GET /V1/snowdog/cmsPage/:pageId/stores
```

What do you think of that?

On the other hand, I found that you can use the **searchCriteria** parameter to filter blocks by given store.

**Comment by anqaka** [comment]
Hi @dariuszmaciejewski. We already have a possibility to get the one page or block by identifier & store ID, but we don't want to connect with Magento API from Vuestorefront to load the CMS block/page. We want to add all CMS block/pages to Vuestorefront "db" - to elasticsearch, like we add products, categories etc... using adapters in https://github.com/DivanteLtd/mage2vuestorefront  . (This repo collect the most important data of Magento store and create base for Vuestorefront). 

So it's good to have one request to collect all but... if you decided it's too complicated from Magento side, I can do it on the adapter level - it will also take some time and will be a little "around" with some more requests but I can make it work. We should decide together which solution will be better. Please let me know what do you think.

**Comment by jochhop** [comment]
Hi @anqaka @dariuszmaciejewski how often will you call magento API to get all stores/blocks? if it won't be too often (because you will have everything indexed in elasticsearch), maybe it worth to create a new endpoint (similar as Darek suggested) but to get all items (pages or blocks) in the following shape:

```
{
   "items": [
       {
           "id": 7,
           "store_ids": [1, 2]
       },
       {
           "id": 11,
           "store_ids": [1, 3]
       }
    ]
}
```

so, you'd need to call 2 different API endpoints for indexing, eg. for blocks:

1) `/rest/V1/snowdog/cmsBlock/search` to get all block items like:

```
{
    "items": [
        {
            "id": 7,
            "identifier": "example-block",
            "title": "Block title",
            "content": "Test block content",
            "creation_time": "2014-12-02 11:54:46",
            "update_time": "2014-12-02 11:54:46",
            "active": true
        },
        {
            "id": 11,
            "identifier": "example-block2",
            "title": "Block title",
            "content": "Test block content",
            "creation_time": "2015-04-30 12:22:24",
            "update_time": "2016-04-04 12:11:57",
            "active": true
        }
     ]
}
```

2) `/rest/V1/snowdog/cmsBlock/searchStores`, which could be also filtered by searchCritera (eg. to get all the stores for a list of block ids)

```
{
   "items": [
       {
           "id": 7,
           "store_ids": [1, 2]
       },
       {
           "id": 11,
           "store_ids": [1, 3]
       }
    ]
}
```

In that way, the implementation in Magento side should not be too complex (at least quicker than create a replication of the original store interface object in Magento with a new field - stores; but still we'll need to add a new type within the extension anyway) and you could link in vuestorefront the blocks and stores.

If this approach doesn't sound good to you, I think the best option is to do it in vuestorefront way

**Comment by mcjwsk** [comment]
@jochhop They need this to data reindexing, so in this case they will need make extra API calls inside loop. It will slow down the process.

>do it in vuestorefront way

What do you mean?

**Comment by jochhop** [comment]
@dariuszmaciejewski Yes, you're right, I know it's not the best approach, but more simple than create a full replicate of magento interfaces to add only 1 field IMO. I meant the workaround proposed above:

> if you decided it's too complicated from Magento side, I can do it on the adapter level - it will also take some time and will be a little "around" with some more requests but I can make it work. We should decide together which solution will be better. Please let me know what do you think.

**Comment by jochhop** [comment]
Closing this, it's already in develop (https://github.com/SnowdogApps/magento2-cms-api/pull/6)
