### ISSUE TITLE
Magento framework version 102.*

### ISSUE THREAD

**Issue by ghost** [SnowdogApps/magento2-cms-api#9]
Currently this module is not satisfiable with magento/framework 102.0.0 since composer requirement is only for version 101.*

Add support for magento/framework 102.*

**Comment by jochhop** [comment]
Hi @ehakio thanks for opening the issue. We have created an internal ticket and we'll check it soon

**Comment by jochhop** [comment]
Thanks again for your suggestion @ehakio , the module has been updated, release 1.4.0 allows the extension to be installed for magento/framework 102.0.*
